In [75]:
import sagemaker
from sagemaker import get_execution_role
import json
import boto3
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/ec2-user/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [76]:
df = pd.read_csv('bbc-text.csv')
##import numpy as np("bbc-text.csv")

In [77]:
df.head()

category                                               text
0           tech  tv future in the hands of viewers with home th...
1       business  worldcom boss  left books alone  former worldc...
2          sport  tigers wary of farrell  gamble  leicester say ...
3          sport  yeading face newcastle in fa cup premiership s...
4  entertainment  ocean s twelve raids box office ocean s twelve...

In [78]:
docs = df['text']

In [79]:
docs.head()

0    tv future in the hands of viewers with home th...
1    worldcom boss  left books alone  former worldc...
2    tigers wary of farrell  gamble  leicester say ...
3    yeading face newcastle in fa cup premiership s...
4    ocean s twelve raids box office ocean s twelve...
Name: text, dtype: object

In [80]:
counter = sklearn.feature_extraction.text.CountVectorizer(max_features = 150 , stop_words = stopwords.words("english"))

In [81]:
docs_sparse = counter.fit_transform(docs)

In [82]:
features = counter.get_feature_names()

In [83]:
print(features)

['000', '10', '2003', '2004', '2005', 'according', 'added', 'already', 'also', 'around', 'back', 'based', 'bbc', 'best', 'big', 'blair', 'britain', 'british', 'brown', 'business', 'called', 'chief', 'come', 'companies', 'company', 'could', 'country', 'day', 'deal', 'digital', 'director', 'economic', 'economy', 'election', 'end', 'england', 'europe', 'european', 'even', 'expected', 'film', 'firm', 'firms', 'first', 'five', 'former', 'four', 'game', 'games', 'get', 'go', 'going', 'good', 'government', 'great', 'group', 'growth', 'half', 'help', 'high', 'home', 'however', 'including', 'industry', 'international', 'labour', 'last', 'like', 'london', 'long', 'made', 'make', 'many', 'market', 'may', 'million', 'minister', 'mobile', 'money', 'month', 'months', 'move', 'mr', 'much', 'music', 'need', 'net', 'new', 'news', 'next', 'number', 'old', 'one', 'part', 'party', 'people', 'phone', 'place', 'plans', 'play', 'players', 'public', 'put', 'really', 'record', 'report', 'right', 'said', 'sales

In [84]:
bucket = 'sagemaker-jce-eliran'
folder = 'bbc';
features_channel =  folder + '/features/features.txt'

In [85]:
s3 = boto3.client('s3')

In [86]:
import pickle

In [87]:
object_features = pickle.dumps(features)

In [88]:
s3.put_object(Bucket = bucket , Key = features_channel , Body = object_features)

{'ResponseMetadata': {'RequestId': '2A4DE53841D0172D',
  'HostId': 'lbbtctygQ1+KT/NyyzhCKhPMBHTqd9Z0Ye2YCXXXLgIyLBhDYRl+1u6/mC3Y+NV6HVQ1TQsss2w=',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'lbbtctygQ1+KT/NyyzhCKhPMBHTqd9Z0Ye2YCXXXLgIyLBhDYRl+1u6/mC3Y+NV6HVQ1TQsss2w=',
   'x-amz-request-id': '2A4DE53841D0172D',
   'date': 'Sun, 02 Feb 2020 14:08:10 GMT',
   'etag': '"2579ac9e1a45f78265fa6119ba3296d8"',
   'content-length': '0',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'ETag': '"2579ac9e1a45f78265fa6119ba3296d8"'}

In [89]:
print(docs_sparse)

  (0, 77)	1
  (0, 20)	1
  (0, 21)	1
  (0, 38)	1
  (0, 72)	2
  (0, 0)	1
  (0, 73)	1
  (0, 7)	1
  (0, 34)	1
  (0, 82)	2
  (0, 102)	1
  (0, 137)	1
  (0, 145)	1
  (0, 58)	1
  (0, 25)	1
  (0, 55)	1
  (0, 6)	1
  (0, 41)	1
  (0, 107)	3
  (0, 88)	1
  (0, 130)	1
  (0, 12)	3
  (0, 80)	1
  (0, 112)	1
  (0, 114)	1
  :	:
  (2223, 59)	1
  (2224, 100)	1
  (2224, 43)	2
  (2224, 57)	1
  (2224, 103)	2
  (2224, 148)	2
  (2224, 97)	1
  (2224, 144)	1
  (2224, 126)	3
  (2224, 147)	2
  (2224, 89)	1
  (2224, 51)	1
  (2224, 54)	1
  (2224, 66)	1
  (2224, 70)	1
  (2224, 34)	1
  (2224, 6)	1
  (2224, 107)	3
  (2224, 143)	2
  (2224, 8)	1
  (2224, 83)	1
  (2224, 140)	2
  (2224, 99)	1
  (2224, 104)	2
  (2224, 135)	2


In [90]:
docs_arr = docs_sparse.toarray()

In [91]:
print(docs_arr)

[[1 0 0 ... 0 0 2]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 2 0 0]
 ...
 [1 2 0 ... 0 0 0]
 [1 0 0 ... 2 0 0]
 [0 0 0 ... 2 2 0]]


In [92]:
docs_arr_tr = docs_arr.transpose()

In [93]:
print(docs_arr_tr)

[[1 1 0 ... 1 1 0]
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 2 ... 0 2 2]
 [0 0 0 ... 0 0 2]
 [2 0 0 ... 0 0 0]]


In [94]:
docs_df_tr = pd.DataFrame(docs_arr_tr, index = counter.get_feature_names())

In [95]:
print(docs_df_tr)

            0     1     2     3     4     5     6     7     8     9     ...  \
000            1     1     0     0     0     0     0     0     0     0  ...   
10             0     0     0     0     0     0     1     0     1     0  ...   
2003           0     0     0     0     0     0     0     0     0     0  ...   
2004           0     0     0     0     0     0     0     0     0     0  ...   
2005           0     0     0     0     0     0     0     0     0     0  ...   
according      1     0     0     0     1     0     0     0     0     0  ...   
added          1     0     0     0     0     0     0     0     0     0  ...   
already        1     1     0     1     0     0     0     0     0     0  ...   
also           3     0     0     0     0     2     1     0     0     0  ...   
around         0     0     0     0     0     0     0     0     0     0  ...   
back           0     0     1     0     0     2     1     1     1     0  ...   
based          0     0     0     0     0     0     0

In [96]:
docs_df = docs_df_tr.transpose()

In [97]:
print(docs_df)

      000  10  2003  2004  2005  according  added  already  also  around  ...  \
0       1   0     0     0     0          1      1        1     3       0  ...   
1       1   0     0     0     0          0      0        1     0       0  ...   
2       0   0     0     0     0          0      0        0     0       0  ...   
3       0   0     0     0     0          0      0        1     0       0  ...   
4       0   0     0     0     0          1      0        0     0       0  ...   
5       0   0     0     0     0          0      0        0     2       0  ...   
6       0   1     0     0     0          0      0        0     1       0  ...   
7       0   0     0     0     0          0      0        0     0       0  ...   
8       0   1     0     0     0          0      0        0     0       0  ...   
9       0   0     0     0     0          0      0        0     0       0  ...   
10      0   0     0     0     0          0      1        0     1       0  ...   
11      0   1     0     3   

In [98]:
#Lesson 9

In [99]:
#fun who cat by col, from 0 until 1

In [100]:
category = df.iloc[:,0:1]

In [101]:
category.head()

category
0           tech
1       business
2          sport
3          sport
4  entertainment

In [102]:
#ייצוג  הקטגוריות באמצעות מספרים

In [103]:
category['category_cat'] = pd.Categorical(category['category'])

In [104]:
category.head()

category   category_cat
0           tech           tech
1       business       business
2          sport          sport
3          sport          sport
4  entertainment  entertainment

In [105]:
dict(enumerate(category['category_cat'].cat.categories))

{0: 'business', 1: 'entertainment', 2: 'politics', 3: 'sport', 4: 'tech'}

In [106]:
category['code'] = category['category_cat'].cat.codes

In [107]:
category.head()

category   category_cat  code
0           tech           tech     4
1       business       business     0
2          sport          sport     3
3          sport          sport     3
4  entertainment  entertainment     1

In [108]:
docs_df.insert(loc = 0 , column = 'category' , value = category['code'])

In [109]:
docs_df.head()

category  000  10  2003  2004  2005  according  added  already  also  ...  \
0         4    1   0     0     0     0          1      1        1     3  ...   
1         0    1   0     0     0     0          0      0        1     0  ...   
2         3    0   0     0     0     0          0      0        0     0  ...   
3         3    0   0     0     0     0          0      0        1     0  ...   
4         1    0   0     0     0     0          1      0        0     0  ...   

   want  way  week  well  win  work  world  would  year  years  
0     7    2     0     1    0     1      0      0     0      2  
1     0    0     0     0    0     0      0      0     0      0  
2     0    1     0     0    0     0      0      2     0      0  
3     0    0     0     0    1     0      0      0     0      0  
4     0    0     1     0    0     0      0      0     0      0  

[5 rows x 151 columns]

In [110]:
np.random.seed(5)

In [111]:
l = list(docs_df.index)

In [112]:
np.random.shuffle(l)

In [113]:
docs_df = docs_df.iloc[l]

In [114]:
docs_df.head()

category  000  10  2003  2004  2005  according  added  already  also  \
219          2    0   0     0     0     0          0      0        1     2   
578          3    0   1     0     0     1          0      0        0     1   
1008         3    0   0     0     0     0          0      1        0     0   
987          1    0   0     0     0     0          0      0        1     1   
1047         1    0   0     0     0     0          0      0        0     0   

      ...  want  way  week  well  win  work  world  would  year  years  
219   ...     0    1     0     0    0     0      0      2     0      0  
578   ...     0    0     0     0    0     0      2      0     1      0  
1008  ...     0    0     1     0    0     0      0      0     1      0  
987   ...     0    0     1     1    0     0      3      1     2      0  
1047  ...     0    0     0     0    0     1      0      0     1      0  

[5 rows x 151 columns]

In [115]:
nrows = docs_df.shape[0]

In [116]:
nrows

2225

In [117]:
ntrain = int(0.7*nrows)

In [118]:
ntrain

1557

In [119]:
docs_df_train = docs_df[:ntrain]

In [120]:
docs_df_test = docs_df[ntrain:]

In [121]:
docs_df_train.shape , docs_df_test.shape

((1557, 151), (668, 151))

In [122]:
docs_df_train.to_csv('bbc_train.csv' , index = False , header = False)

In [123]:
docs_df_test.to_csv('bbc_test.csv' , index = False , header = False)

In [124]:
bucket = 'sagemaker-jce-eliran'

In [125]:
folder = 'bbc'

In [126]:
train_channel = folder + '/train'

In [127]:
validation_channel = folder + '/validation'

In [128]:
sess = sagemaker.Session()

In [129]:
sess.upload_data(path = 'bbc_train.csv' , bucket = bucket , key_prefix = train_channel)

's3://sagemaker-jce-eliran/bbc/train/bbc_train.csv'

In [130]:
sess.upload_data(path = 'bbc_test.csv' , bucket = bucket , key_prefix = validation_channel)

's3://sagemaker-jce-eliran/bbc/validation/bbc_test.csv'

In [131]:
s3_train_data = 's3://{}/{}'.format(bucket , train_channel)

In [132]:
s3_train_data

's3://sagemaker-jce-eliran/bbc/train'

In [133]:
s3_test_data = 's3://{}/{}'.format(bucket , validation_channel)

In [134]:
s3_test_data

's3://sagemaker-jce-eliran/bbc/validation'

In [135]:
s3_output_location = 's3://{}/{}'.format(bucket , folder)

In [136]:
s3_output_location

's3://sagemaker-jce-eliran/bbc'

In [137]:
#containars where the algorithm resides 
containers = {'us-west-2': '433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:latest',
              'us-east-1': '811284229777.dkr.ecr.us-east-1.amazonaws.com/xgboost:latest',
              'us-east-2': '825641698319.dkr.ecr.us-east-2.amazonaws.com/xgboost:latest',
              'eu-west-1': '685385470294.dkr.ecr.eu-west-1.amazonaws.com/xgboost:latest'}


In [138]:
role = get_execution_role()

In [139]:
estimator = sagemaker.estimator.Estimator(containers[boto3.Session().region_name],
                                       role, 
                                       train_instance_count=1, 
                                       train_instance_type='ml.m4.xlarge',
                                       output_path=s3_output_location,
                                       sagemaker_session=sess,
                                       base_job_name ='xgboost-bbc-v1')




In [140]:
estimator.set_hyperparameters(max_depth=5,
                              objective="multi:softmax",
                              num_class=5,
                              num_round=50)


In [141]:

training_input_config = sagemaker.session.s3_input(s3_data=s3_train_data,content_type="csv")
validation_input_config = sagemaker.session.s3_input(s3_data=s3_test_data,content_type="csv")

In [142]:

estimator.fit({'train':training_input_config, 'validation':validation_input_config})

2020-02-02 14:08:25 Starting - Starting the training job...
2020-02-02 14:08:26 Starting - Launching requested ML instances......
2020-02-02 14:09:32 Starting - Preparing the instances for training......
2020-02-02 14:10:36 Downloading - Downloading input data...
2020-02-02 14:11:26 Training - Training image download completed. Training in progress..Arguments: train
[2020-02-02:14:11:27:INFO] Running standalone xgboost training.
[2020-02-02:14:11:27:INFO] File size need to be processed in the node: 0.64mb. Available memory size in the node: 8518.23mb
[2020-02-02:14:11:27:INFO] Determined delimiter of CSV input is ','
[14:11:27] S3DistributionType set as FullyReplicated
[14:11:27] 1557x150 matrix with 233550 entries loaded from /opt/ml/input/data/train?format=csv&label_column=0&delimiter=,
[2020-02-02:14:11:27:INFO] Determined delimiter of CSV input is ','
[14:11:27] S3DistributionType set as FullyReplicated
[14:11:27] 668x150 matrix with 100200 entries loaded from /opt/ml/input/data/va

In [143]:
predictor = estimator.deploy(initial_instance_count = 1,
                            instance_type = "ml.t2.medium",
                            endpoint_name = "bbc-xgboost-jce")

---------------------!